const soundcloud = {
  id: 21877470,
  kind: 'user',
  permalink: 'sizzur_dlx',
  username: 'Sizzur_DLX',
  last_modified: '2016/10/04 04:21:48 +0000',
  uri: 'https://api.soundcloud.com/users/21877470',
  permalink_url: 'http://soundcloud.com/sizzur_dlx',
  avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
  country: 'United States',
  first_name: 'Sizzur',
  last_name: 'DLX',
  full_name: 'Sizzur DLX',
  description: null,
  city: 'Columbus',
  discogs_name: null,
  myspace_name: null,
  website: null,
  website_title: null,
  track_count: 18,
  playlist_count: 2,
  online: false,
  plan: 'Free',
  subscriptions: [],
  followers_count: 54,
  followings_count: 110,
  public_favorites_count: 265,
  reposts_count: 12,
  tracks: [
    {
      kind: 'track',
      id: 290849985,
      created_at: '2016/10/31 19:33:10 +0000',
      user_id: 21877470,
      duration: 235959,
      commentable: true,
      state: 'finished',
      original_content_size: 3743230,
      last_modified: '2016/10/31 19:33:10 +0000',
      sharing: 'public',
      tag_list: '',
      permalink: '2016-10-17-onebluefaceoutlookcom2-master-1',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: '',
      title: '2016 - 10 - 17 Oneblueface@outlook.com(2) - Master - 1',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'm4a',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/290849985',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/2016-10-17-onebluefaceoutlookcom2-master-1',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/290849985/stream',
      download_url: 'https://api.soundcloud.com/tracks/290849985/download',
      playback_count: 69,
      download_count: 0,
      favoritings_count: 6,
      reposts_count: 1,
      comment_count: 0,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/1FnCkbC8QzRD_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/290849985/attachments',
    },
    {
      kind: 'track',
      id: 290849981,
      created_at: '2016/10/31 19:33:08 +0000',
      user_id: 21877470,
      duration: 235959,
      commentable: true,
      state: 'finished',
      original_content_size: 3815564,
      last_modified: '2016/10/31 19:33:08 +0000',
      sharing: 'public',
      tag_list: '',
      permalink: '2016-10-17-onebluefaceoutlookcom3-master-1',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: '',
      title: '2016 - 10 - 17 Oneblueface@outlook.com(3) - Master - 1',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'm4a',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/290849981',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/2016-10-17-onebluefaceoutlookcom3-master-1',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/290849981/stream',
      download_url: 'https://api.soundcloud.com/tracks/290849981/download',
      playback_count: 27,
      download_count: 0,
      favoritings_count: 0,
      reposts_count: 1,
      comment_count: 0,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/01jgUEN63VIP_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/290849981/attachments',
    },
    {
      kind: 'track',
      id: 290849977,
      created_at: '2016/10/31 19:33:06 +0000',
      user_id: 21877470,
      duration: 169759,
      commentable: true,
      state: 'finished',
      original_content_size: 2692870,
      last_modified: '2016/10/31 19:33:06 +0000',
      sharing: 'public',
      tag_list: '',
      permalink: '2016-10-17-onebluefaceoutlookcom4-master',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: '',
      title: '2016 - 10 - 17 Oneblueface@outlook.com(4) - Master',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'm4a',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/290849977',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/2016-10-17-onebluefaceoutlookcom4-master',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/290849977/stream',
      download_url: 'https://api.soundcloud.com/tracks/290849977/download',
      playback_count: 31,
      download_count: 0,
      favoritings_count: 0,
      reposts_count: 1,
      comment_count: 0,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/8o3FsHVm3ndP_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/290849977/attachments',
    },
    {
      kind: 'track',
      id: 290848453,
      created_at: '2016/10/31 19:23:57 +0000',
      user_id: 21877470,
      duration: 320108,
      commentable: true,
      state: 'finished',
      original_content_size: 5244395,
      last_modified: '2016/10/31 19:23:57 +0000',
      sharing: 'public',
      tag_list: '',
      permalink: '2016-05-17-sizzurdlx-x-master-1',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: '',
      title: '2016 - 05 - 17 SIZZURDLX X - Master',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'm4a',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/290848453',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/2016-05-17-sizzurdlx-x-master-1',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/290848453/stream',
      download_url: 'https://api.soundcloud.com/tracks/290848453/download',
      playback_count: 26,
      download_count: 0,
      favoritings_count: 1,
      reposts_count: 0,
      comment_count: 0,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/Zz2S032CSzaB_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/290848453/attachments',
    },
    {
      kind: 'track',
      id: 277685145,
      created_at: '2016/08/10 17:40:37 +0000',
      user_id: 21877470,
      duration: 257068,
      commentable: true,
      state: 'finished',
      original_content_size: 45329570,
      last_modified: '2016/08/10 17:40:37 +0000',
      sharing: 'public',
      tag_list: '',
      permalink: 'untitled1',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Hip-hop & Rap',
      title: 'Untitled1',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'wav',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/277685145',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/untitled1',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/277685145/stream',
      download_url: 'https://api.soundcloud.com/tracks/277685145/download',
      playback_count: 91,
      download_count: 0,
      favoritings_count: 3,
      reposts_count: 0,
      comment_count: 0,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/hTcsQHGvmomV_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/277685145/attachments',
    },
    {
      kind: 'track',
      id: 277685140,
      created_at: '2016/08/10 17:40:37 +0000',
      user_id: 21877470,
      duration: 569757,
      commentable: true,
      state: 'finished',
      original_content_size: 100483030,
      last_modified: '2016/08/10 17:42:26 +0000',
      sharing: 'public',
      tag_list: '',
      permalink: 'untitled2',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Hip-hop & Rap',
      title: 'Untitled2',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'wav',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/277685140',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/untitled2',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/277685140/stream',
      download_url: 'https://api.soundcloud.com/tracks/277685140/download',
      playback_count: 47,
      download_count: 0,
      favoritings_count: 0,
      reposts_count: 0,
      comment_count: 0,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/0Nr9KTK5xCvr_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/277685140/attachments',
    },
    {
      kind: 'track',
      id: 264672227,
      created_at: '2016/05/18 03:59:29 +0000',
      user_id: 21877470,
      duration: 320108,
      commentable: true,
      state: 'finished',
      original_content_size: 5244395,
      last_modified: '2016/05/18 03:59:43 +0000',
      sharing: 'public',
      tag_list: '',
      permalink: '2016-05-17-sizzurdlx-x-master',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Hip-hop & Rap',
      title: '2016 - 05 - 17 SIZZURDLX X - Master',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'm4a',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/264672227',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/2016-05-17-sizzurdlx-x-master',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/264672227/stream',
      download_url: 'https://api.soundcloud.com/tracks/264672227/download',
      playback_count: 62,
      download_count: 0,
      favoritings_count: 5,
      reposts_count: 1,
      comment_count: 0,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/62awqkAwHUBK_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/264672227/attachments',
    },
    {
      kind: 'track',
      id: 248801259,
      created_at: '2016/02/25 06:21:14 +0000',
      user_id: 21877470,
      duration: 279561,
      commentable: true,
      state: 'finished',
      original_content_size: 3559611,
      last_modified: '2016/02/25 06:21:14 +0000',
      sharing: 'public',
      tag_list: '',
      permalink: '2016-02-14a',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Hip Hop',
      title: '2016 - 02 - 14',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'm4a',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/248801259',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/2016-02-14a',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/248801259/stream',
      download_url: 'https://api.soundcloud.com/tracks/248801259/download',
      playback_count: 69,
      download_count: 0,
      favoritings_count: 7,
      reposts_count: 0,
      comment_count: 1,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/8wlk3XpNmusJ_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/248801259/attachments',
    },
    {
      kind: 'track',
      id: 248801253,
      created_at: '2016/02/25 06:21:12 +0000',
      user_id: 21877470,
      duration: 283455,
      commentable: true,
      state: 'finished',
      original_content_size: 2676294,
      last_modified: '2016/02/25 06:21:13 +0000',
      sharing: 'public',
      tag_list: '',
      permalink: '2016-02-15a',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Hip Hop',
      title: '2016 - 02 - 15',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'm4a',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/248801253',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/2016-02-15a',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/248801253/stream',
      download_url: 'https://api.soundcloud.com/tracks/248801253/download',
      playback_count: 39,
      download_count: 0,
      favoritings_count: 5,
      reposts_count: 0,
      comment_count: 0,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/veKtFi88wAtX_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/248801253/attachments',
    },
    {
      kind: 'track',
      id: 248801236,
      created_at: '2016/02/25 06:21:05 +0000',
      user_id: 21877470,
      duration: 154058,
      commentable: true,
      state: 'finished',
      original_content_size: 2381548,
      last_modified: '2016/02/25 06:21:05 +0000',
      sharing: 'public',
      tag_list: '',
      permalink: '2016-02-19a',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Hip Hop',
      title: '2016 - 02 - 19',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'm4a',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/248801236',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/2016-02-19a',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/248801236/stream',
      download_url: 'https://api.soundcloud.com/tracks/248801236/download',
      playback_count: 50,
      download_count: 0,
      favoritings_count: 2,
      reposts_count: 0,
      comment_count: 0,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/pmazfl88n3rR_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/248801236/attachments',
    },
    {
      kind: 'track',
      id: 169106494,
      created_at: '2014/09/24 03:03:11 +0000',
      user_id: 21877470,
      duration: 160145,
      commentable: true,
      state: 'finished',
      original_content_size: 5290515,
      last_modified: '2014/09/24 03:03:11 +0000',
      sharing: 'public',
      tag_list: 'Sample Beat Beats Instrumental "Instrumental Hip Hop" Trap sin',
      permalink: '016-sin',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Hip Hop',
      title: '016 - Sin',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'm4a',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/169106494',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/016-sin',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/169106494/stream',
      download_url: 'https://api.soundcloud.com/tracks/169106494/download',
      playback_count: 52,
      download_count: 0,
      favoritings_count: 4,
      reposts_count: 0,
      comment_count: 1,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/VZ8Hx6PTgxqz_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/169106494/attachments',
    },
    {
      kind: 'track',
      id: 156808998,
      created_at: '2014/07/01 09:22:43 +0000',
      user_id: 21877470,
      duration: 292963,
      commentable: true,
      state: 'finished',
      original_content_size: 77496488,
      last_modified: '2014/09/06 13:56:27 +0000',
      sharing: 'public',
      tag_list: 'siz dlx sizzurdlx instrumental trap beats "trap beats" "Hip Hop" rap bass "Dirty South" 808',
      permalink: 'trap-two-109-beat',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'sizzur',
      title: 'Trap Two - 109 - Beat',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'wav',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/156808998',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/trap-two-109-beat',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/156808998/stream',
      download_url: 'https://api.soundcloud.com/tracks/156808998/download',
      playback_count: 71,
      download_count: 0,
      favoritings_count: 2,
      reposts_count: 0,
      comment_count: 0,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/Qs1XXOC9rdjx_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/156808998/attachments',
    },
    {
      kind: 'track',
      id: 155109362,
      created_at: '2014/06/19 18:18:16 +0000',
      user_id: 21877470,
      duration: 259131,
      commentable: true,
      state: 'finished',
      original_content_size: 74605796,
      last_modified: '2014/09/06 13:56:27 +0000',
      sharing: 'public',
      tag_list: 'Instrumental Hip-Hop Rap beat beats 808 sizzur siz',
      permalink: 'trap-two-108-beat',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Trap',
      title: 'Trap Two - 108 - Beat',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'wav',
      license: 'cc-by',
      uri: 'https://api.soundcloud.com/tracks/155109362',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/trap-two-108-beat',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/155109362/stream',
      download_url: 'https://api.soundcloud.com/tracks/155109362/download',
      playback_count: 65,
      download_count: 6,
      favoritings_count: 1,
      reposts_count: 0,
      comment_count: 1,
      downloadable: true,
      waveform_url: 'https://w1.sndcdn.com/9lOB2lernr55_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/155109362/attachments',
    },
    {
      kind: 'track',
      id: 140169483,
      created_at: '2014/03/18 11:13:28 +0000',
      user_id: 21877470,
      duration: 337820,
      commentable: true,
      state: 'finished',
      original_content_size: 6755335,
      last_modified: '2014/09/06 13:56:28 +0000',
      sharing: 'public',
      tag_list: 'Beats Beat rap "Hip Hop" hip hop trap south dirty "dirty south" Bass boosted dope work',
      permalink: '73-aww',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Instrumental',
      title: '#73 - Aww',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'mp3',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/140169483',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/73-aww',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/140169483/stream',
      download_url: 'https://api.soundcloud.com/tracks/140169483/download',
      playback_count: 44,
      download_count: 1,
      favoritings_count: 1,
      reposts_count: 0,
      comment_count: 0,
      downloadable: true,
      waveform_url: 'https://w1.sndcdn.com/eTGbfz3FCqsV_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/140169483/attachments',
    },
    {
      kind: 'track',
      id: 140169356,
      created_at: '2014/03/18 11:12:01 +0000',
      user_id: 21877470,
      duration: 241968,
      commentable: true,
      state: 'finished',
      original_content_size: 4838470,
      last_modified: '2014/09/06 13:56:28 +0000',
      sharing: 'public',
      tag_list: 'Beats Beat rap "Hip Hop" hip hop trap south dirty "dirty south" Bass boosted dope work',
      permalink: '66-rnb',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Instrumental',
      title: '#66 - RnB',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'mp3',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/140169356',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/66-rnb',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/140169356/stream',
      download_url: 'https://api.soundcloud.com/tracks/140169356/download',
      playback_count: 67,
      download_count: 2,
      favoritings_count: 1,
      reposts_count: 0,
      comment_count: 0,
      downloadable: true,
      waveform_url: 'https://w1.sndcdn.com/S24UQnroVvY7_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/140169356/attachments',
    },
    {
      kind: 'track',
      id: 140169354,
      created_at: '2014/03/18 11:12:00 +0000',
      user_id: 21877470,
      duration: 227025,
      commentable: true,
      state: 'finished',
      original_content_size: 4539629,
      last_modified: '2014/09/06 13:56:29 +0000',
      sharing: 'public',
      tag_list: 'Beats Beat rap "Hip Hop" hip hop trap south dirty "dirty south" Bass boosted dope work',
      permalink: '63-epic',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Instrumental',
      title: '#63 - Epic',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'mp3',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/140169354',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/63-epic',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/140169354/stream',
      download_url: 'https://api.soundcloud.com/tracks/140169354/download',
      playback_count: 53,
      download_count: 2,
      favoritings_count: 2,
      reposts_count: 0,
      comment_count: 0,
      downloadable: true,
      waveform_url: 'https://w1.sndcdn.com/EVC53v1KT87H_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/140169354/attachments',
    },
    {
      kind: 'track',
      id: 140169353,
      created_at: '2014/03/18 11:12:00 +0000',
      user_id: 21877470,
      duration: 267936,
      commentable: true,
      state: 'finished',
      original_content_size: 5357784,
      last_modified: '2014/09/06 13:56:29 +0000',
      sharing: 'public',
      tag_list: 'Beats Beat rap "Hip Hop" hip hop trap south dirty "dirty south" Bass boosted dope work',
      permalink: '45-grip',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Instrumental',
      title: '#45 - Grip',
      description: '',
      label_name: null,
      release: null,
      track_type: null,
      key_signature: null,
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'mp3',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/140169353',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/45-grip',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/140169353/stream',
      download_url: 'https://api.soundcloud.com/tracks/140169353/download',
      playback_count: 57,
      download_count: 2,
      favoritings_count: 1,
      reposts_count: 0,
      comment_count: 0,
      downloadable: true,
      waveform_url: 'https://w1.sndcdn.com/PcAwZIPIDSfM_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/140169353/attachments',
    },
    {
      kind: 'track',
      id: 90666327,
      created_at: '2013/05/04 01:46:32 +0000',
      user_id: 21877470,
      duration: 188150,
      commentable: true,
      state: 'finished',
      original_content_size: 7524379,
      last_modified: '2014/09/06 13:56:30 +0000',
      sharing: 'public',
      tag_list: 'umental instr instrumentals beat beats beatsforsale get up trap trapmusic',
      permalink: 'getup',
      streamable: true,
      embeddable_by: 'all',
      purchase_url: null,
      purchase_title: null,
      label_id: null,
      genre: 'Hip-hop/rap',
      title: 'Get up',
      description: '',
      label_name: 'DLX Studios',
      release: '',
      track_type: 'recording',
      key_signature: '',
      isrc: null,
      video_url: null,
      bpm: null,
      release_year: null,
      release_month: null,
      release_day: null,
      original_format: 'mp3',
      license: 'all-rights-reserved',
      uri: 'https://api.soundcloud.com/tracks/90666327',
      user: {
        id: 21877470,
        kind: 'user',
        permalink: 'sizzur_dlx',
        username: 'Sizzur_DLX',
        last_modified: '2016/10/04 04:21:48 +0000',
        uri: 'https://api.soundcloud.com/users/21877470',
        permalink_url: 'http://soundcloud.com/sizzur_dlx',
        avatar_url: 'https://i1.sndcdn.com/avatars-000046505750-5nyojf-large.jpg',
      },
      permalink_url: 'https://soundcloud.com/sizzur_dlx/getup',
      artwork_url: null,
      stream_url: 'https://api.soundcloud.com/tracks/90666327/stream',
      download_url: 'https://api.soundcloud.com/tracks/90666327/download',
      playback_count: 64,
      download_count: 0,
      favoritings_count: 2,
      reposts_count: 0,
      comment_count: 0,
      downloadable: false,
      waveform_url: 'https://w1.sndcdn.com/VHv9BLbw5o4m_m.png',
      attachments_uri: 'https://api.soundcloud.com/tracks/90666327/attachments',
    },
  ],
};

export default soundcloud;
